### ISSUE TITLE
recycler output

### ISSUE THREAD

**Issue by cytang19** [rozovr/Recycler#1]
Hi,

I am trying to use your program. There is no description on the output so I am not sure if I am doing correctly. My output is a text file with all the EDGEs, for ex: 
('EDGE_132_length_60_cov_85', 'EDGE_623_length_203_cov_23.7027').

Is this suppose to be the output? Do you have a way where I can extract the sequence from the fastg file?

Thanks,
Cheng

**Comment by rozovr** [comment]
Hi Cheng, 

thanks for the feedback. I updated the README on the front page here to describe the outputs. I suspect what you are seeing is file <prefix>.cycs.paths_w_cov.txt. The sequences are in a separate file that should be labeled <prefix>.cycs.fasta.

Best, Roye

**Comment by cytang19** [comment]
Hi Roye,

I didn't realise there are 2 output files until now that you told me. All the time I was seeing only the screen output. Thanks for your help.

Cheers,
Cheng
