### ISSUE TITLE
minor typo in 'Preparing the BAM input:'

### ISSUE THREAD

**Issue by cameronmartino** [rozovr/Recycler#15]
Using samtools Version: 0.1.19

samtools sort reads_pe_primary.bam > reads_pe_primary.sort.bam

I believe should be .. 

samtools sort reads_pe_primary.bam reads_pe_primary.sort

**Comment by jnesme** [comment]
I concur

**Comment by dpellow** [comment]
Fixed in README. Thanks for pointing it out!
