### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by peng-ye** [rozovr/Recycler#29]
Hello. Thanks for introducing such a wonderful tool.
Recently I tried to apply Recycler in several isolate sequence data, yet some of them got this error. Any idea how I fix this?
`Traceback (most recent call last):
  File "Recycler/bin/recycle.py", line 131, in <module>
    paths = enum_high_mass_shortest_paths(COMP)
  File "recyclelib/utils.py", line 242, in enum_high_mass_shortest_paths
    G.add_edge(e[0], e[1], cost = 1./get_spades_base_mass(G, e[0]))
ZeroDivisionError: float division by zero
`

**Comment by dpellow** [comment]
Thanks for your interest! What version of Recycler are you working with? Can you give us a minimal example which causes this error and we'll be able to look into it more.

**Comment by dpellow** [comment]
This issue should be fixed now.
Thanks for the feedback!
