### ISSUE TITLE
Support for assembly graphs in .gfa format

### ISSUE THREAD

**Issue by caspargross** [rozovr/Recycler#30]
Many assemblers create assembly graphs as .gfa file.
Are there plans to support this file format in the future? Can you recommend any conversion tools in the meantime? 
Thanks for creating this tool!

**Comment by dpellow** [comment]
Thanks for your interest!
Right now there are no plans to support gfa but I can look into this and also conversion tools. A quick search didn't turn up any obvious tools for this.

**Comment by hafizmtalha** [comment]
Do we have any update on this ? is the tool has support of gfa file now or not ?

**Comment by dpellow** [comment]
Thanks for your interest in Recycler - right now the tool does not support gfa format, but a future version of Recycler might include gfa support.
