### ISSUE TITLE
Recycler with Bowtie2 and MEGAHIT

### ISSUE THREAD

**Issue by Russel88** [rozovr/Recycler#31]
Hi,

Not an issue really, I just want to let you know that Recycler worked seamlessly for me with using Bowtie2 (2.3.4.1) for creating the BAM file and MEGAHIT (1.1.3) for the fastg file.

Thank you for a great tool.

Cheers,
Jakob

**Comment by dpellow** [comment]
Thanks for the feedback, we're glad the tool was able to help you!
