### ISSUE TITLE
Empty output files

### ISSUE THREAD

**Issue by LPerlaza** [rozovr/Recycler#38]
Hi everyone,

I am running recycler and I am getting empty outputs. I am no sure what I am doing wrong because all the steps before running Recycler seem to run fine. I am sure that there is a plasmid in my sequencing data, so I am not sure why the empty outputs. Could you please send me some tips to troubleshoot this? Thanks!

Laura

**Comment by dpellow** [comment]
Thanks for your interest in using Recycler. If the output files are empty it means that Recycler did not find any predicted plasmid sequences in the input. There are a few reasons why this might happen - if you can send us more information about the inputs we can help with troubleshooting.

What assembler and version are you using?
