### ISSUE TITLE
recycler.py doesn't end (metagenome data) 

### ISSUE THREAD

**Issue by vjoliveira** [rozovr/Recycler#40]
Hi!

I am trying run a metagenome data in Recycler, however the run starts well but never ends (no error is given). I had no problems making the bam file. The terminal looks like this:
"
("NODE_280594_length_1837_cov_7.6655_ID_561187'", 'NODE_662693_length_2433_cov_6.4467_ID_1325385', "NODE_1079610_length_163_cov_6.5000_ID_2159219'", 'NODE_11346_length_524_cov_7.3073_ID_22691')
before [7.6655, 6.4467, 6.5, 7.3073]
after [0.6738814017310526, 0, 0, 0.3156814017310525]
2019-10-04 12:21:56 4  nodes remain in component
2019-10-04 12:21:57 2  nodes remain in component
2019-10-04 12:21:57 3  nodes remain in component
2019-10-04 12:21:57 2  nodes remain in component
2019-10-04 12:21:57 6  nodes remain in component
2019-10-04 12:21:57 15  nodes remain in component"

It ran for 3 days and did not leave this step.

I used Recycle with plasmid data and it went well.

**Comment by ilkaybuysal** [comment]
I'm having the similar issue so I was wondering if anyone has an answer to this?

**Comment by dpellow** [comment]
Is it possible that Recycler is just taking a very long time? How big are the input files?
Our recommendation is to use our new tool, SCAPP which is supposed to replace Recycler for assembling plasmids _in metagenomic samples_. SCAPP: https://github.com/Shamir-Lab/SCAPP

**Comment by ilkaybuysal** [comment]
hi,

yes I did activate it, as you can see:
**(scapp)** uysal@MPLCLTLP0185:~$ scapp -g  ./assembly_graph.fastg -o ./2020_11_14_SCAPP_Plasmid_tool_analyses/ -k 55 -r1 ./MG_176020.R1.fq.gz -r2 ./MG_176020.R1.fq.gz

Command 'scapp' not found, did you mean:

  command 'scapy' from deb python-scapy
  command 'scamp' from deb scamp

Try: sudo apt install <deb name>

**Comment by ilkaybuysal** [comment]
so i basicall did all; these 3 steps:
wget https://raw.githubusercontent.com/Shamir-Lab/SCAPP/master/install_scapp.yaml
conda env create -f install_scapp.yaml
conda activate scapp

is there anything else i need to do to activate it?

**Comment by ilkaybuysal** [comment]
it's 28,9 MB (28 890 693 bytes), so the usual size for a contig file I would say
