### ISSUE TITLE
Using contigs or scaffolds instead of the assembly graph.

### ISSUE THREAD

**Issue by vappiah** [rozovr/Recycler#42]
Is it acceptable if i use the contig.fasta or scaffold.fasta file instead of the assembly graph as specified in the tutorial?

**Comment by dpellow** [comment]
The point of Recycler and it's successor SCAPP is that they use the structure of the assembly graph which encodes much more information than the contigs or scaffolds. These tools will not work with just the contig or scaffold files as these do not include the graph structure.
If you can let us know more about what you're trying to do we can help you run SCAPP or Recycler on your data.

**Comment by vappiah** [comment]
Thanks @dpellow. I have a single-end oxford nanopore reads of mycobacterium ulcerans which I want to identifly plasmids as well as visualize them in a circular function. I would be grateful if you can recommend some pipelines to do that. Thanks

**Comment by dpellow** [comment]
It sounds like you could use a plasmid sequence classifier such as our tool PlasClass, however it has not been tested on long reads. There may be some tools that are specifically for classifying long reads as plasmids.
For visualization you can try the tool called Bandage.

**Comment by vappiah** [comment]
Hi @dpellow. I used SCAPP to predict plasmids from oxford nanopore draft assembly. It turns out that  it was able to make an a good prediction. I blasted the contigs with high proba values and I got a hit from BLAST.
Kudos to the SCAPP team

**Comment by dpellow** [comment]
Great to hear that it worked on 3rd gen sequencing technology! Thanks for letting us know.
