### ISSUE TITLE
Samtools sort changed

### ISSUE THREAD

**Issue by termithorbor** [rozovr/Recycler#46]
Hi,

when I use the following command samtools sort reads_pe_primary.bam reads_pe_primary.sort.bam
I get this error:

[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  --no-PG    do not add a PG line
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
      --verbosity INT
               Set level of verbosity

When I add -o like this samtools sort reads_pe_primary.bam -o reads_pe_primary.sort.bam it is working.
My samtools version is 1.15.

**Comment by dpellow** [comment]
OK. The instructions were tested for the given samtools version noted. You should use the command compatible with your version of samtools. Note that our tool SCAPP aims to replace Recycler for assembling plasmids in metagenomic samples if that is what you are trying to do.
