### ISSUE TITLE
I have a problem when I used recycler

### ISSUE THREAD

**Issue by OAF12** [rozovr/Recycler#5]
This was the commad:  python recycle.py -g assembly_graph.fastg -k 55 -b reads_pe_primary.sort.bam
but I got the below error
 ================== path, coverage levels when added ====================
Traceback (most recent call last):
  File "recycle.py", line 131, in <module>
    last_node_count = len(COMP.nodes())
TypeError: object of type 'generator' has no len()
what should be done to solve this problem?
Thanks

**Comment by rozovr** [comment]
Hi @OAF12 , 

I apologize for taking very long to reply. Did you manage to resolve this issue? If not, can you help me replicate it?

Thanks, R

**Comment by OAF12** [comment]
?Hi,


I didnt manage to solve the problem till now. How you can help me to solve it?


Best regards

Omneya

________________________________

**Comment by rozovr** [comment]
Omneya, 

Since I haven't seen this pop up before, I would suggest first ruling out installation issues. Can you please try to reinstall using bioconda? That should make sure all the dependencies are in place.

Thanks, R
